# Generated by Django 4.2.6 on 2024-02-15 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('valve', '0003_alter_actualite_auteur'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='type_fichier',
            field=models.CharField(blank=True, choices=[('AA', 'Actes administratifs'), ('DT', 'Documents de travail'), ('DI', "Documents d'information"), ('DP', 'Documents patrimoniaux'), ('', 'Documents juridiques'), ('DS', 'Documents scientifiques'), ('DD', 'Documents divers')], max_length=255, null=True),
        ),
    ]
