# Generated by Django 4.2.6 on 2024-02-15 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('valve', '0005_alter_document_type_fichier'),
    ]

    operations = [
        migrations.RenameField(
            model_name='document',
            old_name='type_fichier',
            new_name='type_doc',
        ),
        migrations.RemoveField(
            model_name='document',
            name='nom',
        ),
        migrations.AddField(
            model_name='document',
            name='concerne',
            field=models.TextField(blank=True, max_length=255, null=True),
        ),
    ]
