# Generated by Django 4.2.6 on 2024-02-15 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('valve', '0006_rename_type_fichier_document_type_doc_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='concerne',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
