# Generated by Django 4.2.6 on 2024-02-16 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('valve', '0009_rename_concerne_document_nom_fichier_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='fichier',
            field=models.FileField(upload_to='documents'),
        ),
    ]
