# Generated by Django 4.2.7 on 2024-02-19 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('valve', '0010_alter_document_fichier'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfigImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.ImageField(blank=True, null=True, upload_to='configImage/%Y/%m/%d/')),
                ('iconInsp', models.ImageField(blank=True, null=True, upload_to='configImage/%Y/%m/%d/')),
            ],
        ),
    ]
