# Generated by Django 4.2.7 on 2024-02-19 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('valve', '0011_configimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='configimage',
            name='icon',
            field=models.ImageField(upload_to='images/'),
        ),
    ]
