# Generated by Django 4.2.7 on 2024-02-19 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('valve', '0012_alter_configimage_icon'),
    ]

    operations = [
        migrations.AddField(
            model_name='configimage',
            name='imagepageigf',
            field=models.ImageField(null=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='configimage',
            name='iconInsp',
            field=models.ImageField(upload_to='images/'),
        ),
    ]
