# Generated by Django 4.2.7 on 2024-02-19 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('valve', '0013_configimage_imagepageigf_alter_configimage_iconinsp'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfigImageigf',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagepageigf', models.ImageField(null=True, upload_to='images/')),
            ],
        ),
        migrations.RemoveField(
            model_name='configimage',
            name='imagepageigf',
        ),
    ]
