# Generated by Django 4.2.7 on 2024-02-19 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('valve', '0014_configimageigf_remove_configimage_imagepageigf'),
    ]

    operations = [
        migrations.AlterField(
            model_name='configimageigf',
            name='imagepageigf',
            field=models.ImageField(upload_to='images/'),
        ),
    ]
