# Generated by Django 4.2.7 on 2024-02-20 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('valve', '0017_alter_actualite_categorie'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='type_doc',
            field=models.CharField(blank=True, choices=[('D', 'Décision'), ('NTE', 'Note'), ('CO', 'Communiqué Officiel')], max_length=255, null=True),
        ),
    ]
