# Generated by Django 4.2.7 on 2024-02-20 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('valve', '0019_alter_actualite_categorie_alter_document_type_doc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='taille',
            field=models.CharField(blank=True, choices=[('D', 'Décision'), ('NTE', 'Note'), ('CO', 'Communiqué Officiel'), ('AUT', 'Autres')], max_length=255, null=True),
        ),
    ]
