# Generated by Django 4.2.7 on 2024-02-21 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('valve', '0022_rename_nom_fichier_document_nomdocument'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actualite',
            name='auteur',
            field=models.CharField(blank=True, choices=[('Chef de Service', 'Chef de Service'), ('Chef de Service Adjoint', 'Chef de Service Adjoint'), ('Coordonateur', 'Coordonateur'), ('Coordonateur Adjoint', 'Coordonateur Adjoint'), ('Directeur', 'Directeur'), ('Chef de Division', 'Chef de Division'), ('Chef de Bureau', 'Chef de Bureau'), ('Assistant Directeur', 'Assistant Directeur'), ('Autres', 'Autres')], max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='actualite',
            name='categorie',
            field=models.CharField(blank=True, choices=[("Annonce d'un évenement", "Annonce d'un évenement"), ("Compte rendu d'un évenement à venir", "Compte rendu d'un évenement à venir"), ("Compte rendu d'un évenement passé", "Compte rendu d'un évenement passé"), ('Invitation à un évenement', 'Invitation à un évenement'), ('Avis de Sécurité', 'Avis de Sécurité'), ("Annonce d'un nouveau programme", "Annonce d'un nouveau programme"), ("Annonce d'un évenement", "Annonce d'un évenement"), ('Autres', 'Autres')], max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='document',
            name='type_doc',
            field=models.CharField(blank=True, choices=[('Décision', 'Décision'), ('Note', 'Note'), ('Communiqué Officiel', 'Communiqué Officiel'), ('Autres', 'Autres')], max_length=255, null=True),
        ),
    ]
