# Generated by Django 4.2.7 on 2024-02-21 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('valve', '0023_alter_actualite_auteur_alter_actualite_categorie_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='nomDocument',
        ),
        migrations.AlterField(
            model_name='document',
            name='fichier',
            field=models.FileField(blank=True, null=True, upload_to='document/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='document',
            name='type_doc',
            field=models.CharField(choices=[('Décision', 'Décision'), ('Note', 'Note'), ('Communiqué Officiel', 'Communiqué Officiel'), ('Autres', 'Autres')], max_length=100),
        ),
        migrations.AddField(
            model_name='document',
            name='nomdocument',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
