# Generated by Django 4.2.7 on 2024-02-21 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('valve', '0024_remove_document_nomdocument_alter_document_fichier_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actualite',
            name='titre',
            field=models.CharField(max_length=250),
        ),
    ]
