# Generated by Django 4.2.7 on 2024-02-22 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('valve', '0026_alter_actualite_titre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actualite',
            name='image',
            field=models.ImageField(upload_to='actualités/'),
        ),
    ]
