# Generated by Django 4.2.7 on 2024-02-23 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('valve', '0027_alter_actualite_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actualite',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='actualités/'),
        ),
        migrations.AlterField(
            model_name='document',
            name='type_doc',
            field=models.CharField(choices=[('Décision', 'Décision'), ('Note', 'Note'), ('Communiqué Officiel', 'Communiqué Officiel'), ('Autres', 'Autres'), ('lettre', 'Lettre'), ('Communiqué Interne', 'Communiqué Interne')], max_length=100),
        ),
    ]
