# Generated by Django 4.2.7 on 2024-02-26 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('valve', '0028_alter_actualite_image_alter_document_type_doc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='fichier',
            field=models.FileField(upload_to='documents/%Y/%m/%d/'),
        ),
    ]
