# Generated by Django 4.2.7 on 2024-02-26 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('valve', '0030_alter_document_fichier'),
    ]

    operations = [
        migrations.AlterField(
            model_name='configimageigf',
            name='imagepageigf',
            field=models.ImageField(upload_to='images/'),
        ),
    ]
