# Generated by Django 4.2.7 on 2024-02-26 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('valve', '0031_alter_configimageigf_imagepageigf'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actualite',
            name='image',
            field=models.ImageField(upload_to='images/%Y/%m/%d/'),
        ),
    ]
