# Generated by Django 4.2.7 on 2024-02-26 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('valve', '0032_alter_actualite_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='configimageigf',
            name='imagesaft',
            field=models.ImageField(blank=True, null=True, upload_to='configImage/%Y/%m/%d/'),
        ),
    ]
