# Generated by Django 4.2.7 on 2024-02-27 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('valve', '0034_configimageigf_imageservice1_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TextAccueil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paraphe1', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='configimageigf',
            name='imageaccueil',
            field=models.ImageField(blank=True, null=True, upload_to='configImage/%Y/%m/%d/'),
        ),
    ]
