# Generated by Django 4.2.7 on 2024-02-27 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('valve', '0035_textaccueil_configimageigf_imageaccueil'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfigImageAccueil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imageaccueil', models.ImageField(blank=True, null=True, upload_to='configImage/%Y/%m/%d/')),
            ],
        ),
        migrations.RemoveField(
            model_name='configimageigf',
            name='imageaccueil',
        ),
    ]
