# Generated by Django 4.2.7 on 2024-02-27 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('valve', '0036_configimageaccueil_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='configimageaccueil',
            old_name='imageaccueil',
            new_name='imageaccueil1',
        ),
        migrations.AddField(
            model_name='configimageaccueil',
            name='imageaccueil2',
            field=models.ImageField(blank=True, null=True, upload_to='configImage/%Y/%m/%d/'),
        ),
        migrations.AddField(
            model_name='configimageaccueil',
            name='imageaccueil3',
            field=models.ImageField(blank=True, null=True, upload_to='configImage/%Y/%m/%d/'),
        ),
    ]
