# Generated by Django 4.2.7 on 2024-02-27 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('valve', '0037_rename_imageaccueil_configimageaccueil_imageaccueil1_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TextAnnonceigf',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paragrapheigf1', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
