# Generated by Django 4.2.7 on 2024-02-28 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('valve', '0038_textannonceigf'),
    ]

    operations = [
        migrations.RenameField(
            model_name='textannonceigf',
            old_name='paragrapheigf1',
            new_name='bloc1',
        ),
        migrations.AddField(
            model_name='textannonceigf',
            name='bloc2',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='textannonceigf',
            name='bloc3',
            field=models.TextField(blank=True, null=True),
        ),
    ]
