# Generated by Django 4.2.7 on 2024-02-28 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('valve', '0039_rename_paragrapheigf1_textannonceigf_bloc1_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='data_toggle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('infoDedie_chefBrig', models.TextField(blank=True, null=True)),
                ('infoDedie_igf', models.TextField(blank=True, null=True)),
                ('infoDedie_if', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
