# Generated by Django 4.2.7 on 2024-02-28 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('valve', '0040_data_toggle'),
    ]

    operations = [
        migrations.CreateModel(
            name='TextAnnoncesaft',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blocsaft1', models.TextField(blank=True, null=True)),
                ('blocsaft2', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
