# Generated by Django 4.2.7 on 2024-02-28 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('valve', '0041_textannoncesaft'),
    ]

    operations = [
        migrations.CreateModel(
            name='data_toggle1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('infodediecadre', models.TextField(blank=True, null=True)),
                ('infodediecolla', models.TextField(blank=True, null=True)),
                ('infosenction', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
