# Generated by Django 4.2.7 on 2024-02-28 09:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('valve', '0042_data_toggle1'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='data_toggle1',
            new_name='data_toggleigf',
        ),
        migrations.RenameModel(
            old_name='data_toggle',
            new_name='data_toggleSaft',
        ),
        migrations.RenameField(
            model_name='data_toggleigf',
            old_name='infodediecadre',
            new_name='infoDedie_chefBrig',
        ),
        migrations.RenameField(
            model_name='data_toggleigf',
            old_name='infodediecolla',
            new_name='infoDedie_if',
        ),
        migrations.RenameField(
            model_name='data_toggleigf',
            old_name='infosenction',
            new_name='infoDedie_igf',
        ),
        migrations.RenameField(
            model_name='data_togglesaft',
            old_name='infoDedie_chefBrig',
            new_name='infodediecadre',
        ),
        migrations.RenameField(
            model_name='data_togglesaft',
            old_name='infoDedie_if',
            new_name='infodediecolla',
        ),
        migrations.RenameField(
            model_name='data_togglesaft',
            old_name='infoDedie_igf',
            new_name='infosenction',
        ),
    ]
