# Generated by Django 4.2.7 on 2024-02-28 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('valve', '0043_rename_data_toggle1_data_toggleigf_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Configimageblog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imageblog1', models.ImageField(blank=True, null=True, upload_to='configImage/%Y/%m/%d/')),
                ('imageblog2', models.ImageField(blank=True, null=True, upload_to='configImage/%Y/%m/%d/')),
                ('imageblog3', models.ImageField(blank=True, null=True, upload_to='configImage/%Y/%m/%d/')),
                ('imageblog4', models.ImageField(blank=True, null=True, upload_to='configImage/%Y/%m/%d/')),
                ('imageblog5', models.ImageField(blank=True, null=True, upload_to='configImage/%Y/%m/%d/')),
                ('imageblog6', models.ImageField(blank=True, null=True, upload_to='configImage/%Y/%m/%d/')),
            ],
        ),
    ]
