# Generated by Django 4.2.7 on 2024-02-28 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('valve', '0044_configimageblog'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(blank=True, max_length=250, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('subject', models.CharField(blank=True, max_length=250, null=True)),
                ('message', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
