# Generated by Django 4.2.7 on 2024-02-29 14:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('valve', '0045_contact'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Contact',
            new_name='Suggestion',
        ),
    ]
