# Generated by Django 4.2.7 on 2024-02-29 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('valve', '0046_rename_contact_suggestion'),
    ]

    operations = [
        migrations.CreateModel(
            name='TextProjetParagraph1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre1', models.TextField(blank=True, null=True)),
                ('paragraphe1', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TextProjetParagraph2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre3', models.TextField(blank=True, null=True)),
                ('paragraphe3', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TextProjetParagraph4',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre4', models.TextField(blank=True, null=True)),
                ('paragraphe4', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
