# Generated by Django 4.2.7 on 2024-02-29 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('valve', '0047_textprojetparagraph1_textprojetparagraph2_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TextProjetParagraph3',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre3', models.TextField(blank=True, null=True)),
                ('paragraphe3', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.RenameField(
            model_name='textprojetparagraph2',
            old_name='paragraphe3',
            new_name='paragraphe2',
        ),
        migrations.RenameField(
            model_name='textprojetparagraph2',
            old_name='titre3',
            new_name='titre2',
        ),
    ]
