# Generated by Django 4.2.7 on 2024-02-29 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('valve', '0048_textprojetparagraph3_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='textprojetparagraph1',
            name='titre1',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='textprojetparagraph2',
            name='titre2',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='textprojetparagraph3',
            name='titre3',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='textprojetparagraph4',
            name='titre4',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
