# Generated by Django 4.2.7 on 2024-03-01 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('valve', '0049_alter_textprojetparagraph1_titre1_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Configimageblog1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imageblog1', models.ImageField(blank=True, null=True, upload_to='configImage/%Y/%m/%d/')),
                ('titreblog1', models.ImageField(blank=True, null=True, upload_to='configImage/%Y/%m/%d/')),
                ('parablog1', models.ImageField(blank=True, null=True, upload_to='configImage/%Y/%m/%d/')),
            ],
        ),
        migrations.DeleteModel(
            name='Configimageblog',
        ),
    ]
