# Generated by Django 4.2.7 on 2024-03-01 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('valve', '0051_alter_configimageblog1_parablog1_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Configimageblog2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imageblog2', models.ImageField(blank=True, null=True, upload_to='configImage/%Y/%m/%d/')),
                ('titreblog2', models.CharField(blank=True, max_length=250, null=True)),
                ('parablog2', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
