# Generated by Django 4.2.7 on 2024-03-01 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('valve', '0052_configimageblog2'),
    ]

    operations = [
        migrations.AddField(
            model_name='configimageblog1',
            name='dateblog1',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
