# Generated by Django 4.2.7 on 2024-03-01 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('valve', '0053_configimageblog1_dateblog1'),
    ]

    operations = [
        migrations.AddField(
            model_name='configimageblog2',
            name='dateblog2',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
