# Generated by Django 4.2.7 on 2024-03-01 12:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('valve', '0054_configimageblog2_dateblog2'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Configimageblog2',
        ),
        migrations.DeleteModel(
            name='TextProjetParagraph2',
        ),
        migrations.DeleteModel(
            name='TextProjetParagraph3',
        ),
        migrations.DeleteModel(
            name='TextProjetParagraph4',
        ),
    ]
