# Generated by Django 4.2.7 on 2024-03-04 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('valve', '0055_delete_configimageblog2_delete_textprojetparagraph2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='textprojetparagraph1',
            name='imagesProjet',
            field=models.ImageField(blank=True, null=True, upload_to='configImage/%Y/%m/%d/'),
        ),
    ]
