# Generated by Django 4.2.7 on 2024-03-05 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('valve', '0057_textprojetparagraph1_textimageprojet'),
    ]

    operations = [
        migrations.AddField(
            model_name='configimage',
            name='imageindex',
            field=models.ImageField(default=1, upload_to='images/'),
            preserve_default=False,
        ),
    ]
