# Generated by Django 4.2.7 on 2024-03-05 09:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('valve', '0058_configimage_imageindex'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ConfigImageAccueil',
        ),
    ]
