# Generated by Django 4.2.7 on 2024-03-05 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('valve', '0059_delete_configimageaccueil'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccueilImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imageindex1', models.ImageField(upload_to='images/')),
                ('imageindex2', models.ImageField(upload_to='images/')),
                ('imageindex3', models.ImageField(upload_to='images/')),
            ],
        ),
        migrations.RemoveField(
            model_name='configimage',
            name='imageindex',
        ),
    ]
