# Generated by Django 4.2.7 on 2024-03-05 11:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('valve', '0060_accueilimages_remove_configimage_imageindex'),
    ]

    operations = [
        migrations.RenameField(
            model_name='accueilimages',
            old_name='imageindex1',
            new_name='imageindex',
        ),
        migrations.RemoveField(
            model_name='accueilimages',
            name='imageindex2',
        ),
        migrations.RemoveField(
            model_name='accueilimages',
            name='imageindex3',
        ),
    ]
