# Generated by Django 4.2.7 on 2024-03-05 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('valve', '0061_rename_imageindex1_accueilimages_imageindex_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='IndexImapesParagraphe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imageIndexPara', models.ImageField(upload_to='images/')),
            ],
        ),
    ]
