# Generated by Django 4.2.7 on 2024-03-05 13:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('valve', '0062_indeximapesparagraphe'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='IndexImapesParagraphe',
            new_name='IndexImagesParagraphe',
        ),
    ]
