# Generated by Django 4.2.7 on 2024-03-06 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('valve', '0063_rename_indeximapesparagraphe_indeximagesparagraphe'),
    ]

    operations = [
        migrations.CreateModel(
            name='LogoImgIndex',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logoigfIndex', models.ImageField(blank=True, null=True, upload_to='configImage/%Y/%m/%d/')),
            ],
        ),
    ]
